FROM golang:1.22.4 as build
RUN mkdir -p /scheduler
WORKDIR /scheduler
# Copy dependencies list
# Build with optional lambda.norpc tag
COPY . .
RUN go get -d ./...
RUN go build -tags lambda.norpc -o main main.go
# Copy artifacts to a clean image
FROM public.ecr.aws/lambda/provided:al2023
COPY --from=build /scheduler/main ./main
ENTRYPOINT [ "./main" ]