version = 0.1

[default]
[default.global]
[default.global.parameters]

[default.build.parameters]
cached = true
parallel = true
debug=true

[default.deploy.parameters]
stack_name = "goLangSchedulerAPI"
s3_bucket = "code-pipeline-api-211125399219"
s3_prefix = "api"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
Tag="test"
DomainName="scheduler.page"


[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]

[prod]
[prod.sync]
[prod.sync.parameters]
watch = false