version = 0.1

[default]
[default.global]
[default.global.parameters]
#stack_name = "goLangSchedulerAPO"

[default.build.parameters]
cached = true
parallel = true
[default.deploy.parameters]
stack_name = "goLangSchedulerAPI"
s3_bucket = "tomvisions-scheduler-test"
s3_prefix = "scheduler-dashboard"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[prod]
[prod.sync]
[prod.sync.parameters]
watch = false