AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: An example serverless API and worker written in Golang.

Parameters:
  Stage:
    Type: String
    Description: Bucket for Images
    Default: Stage

Resources:
  ExpressApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      BinaryMediaTypes:
        - image/png
        - image/jpg
        - image/jpeg
        - multipart/form-data
  SchedulerApi:
    Type: AWS::Serverless::Function
    Properties:
    #  CodeUri: ./scheduler-api
      PackageType: Zip
      Runtime: provided.al2
      Handler: lambda.handler
      Timeout: 10
      Events:
  #      RootHandler:
  #        Type: Api
  #        Properties:
  #          Path: '/'
  #          Method: get
        AuthSignIn:
          Type: Api
          Properties:
            Path: '/auth/sign-in'
            Method: post
        AuthSignOut:
          Type: Api
          Properties:
            Path: '/auth/sign-out'
            Method: post
    Metadata:
      BuildMethod: makefile
Outputs:
  Endpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
