AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: An example serverless API and worker written in Golang.

Resources:

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 15

  Api:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.21
      Handler: api
      Timeout: 10
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt Queue.QueueName
      Environment:
        Variables:
          QUEUE_URL: !Ref Queue
      Events:
        RootHandler:
          Type: Api
          Properties:
            Path: '/'
            Method: get
        AuthSignIn:
          Type: Api
          Properties:
            Path: '/auth/sign-in'
            Method: post
        AuthSignOut:
          Type: Api
          Properties:
            Path: '/auth/sign-out'
            Method: post
Outputs:
  Endpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  QueueUrl:
    Value: !Ref Queue
  DeadLetterQueueUrl:
    Value: !Ref DeadLetterQueue