AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: An example serverless API and worker written in Golang.

Parameters:
  Stage:
    Type: String
    Description: Bucket for Images
    Default: stage
  Tag:
    Type: String
    Description: Tag for repo
    Default: $Tag


Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      BinaryMediaTypes:
        - image/png
        - image/jpg
        - image/jpeg
        - multipart/form-data
  SchedulerApi:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::211125399219:role/lambda-role
      ImageUri: !Sub '211125399219.dkr.ecr.us-east-1.amazonaws.com/golang:${Tag}'
      PackageType: Image
      CodeUri: .
  #    Runtime: provided.al2023
  #    Handler: lambda.handler
      Timeout: 10
      Events:
      #  RootHandler:
      #    Type: Api
     #     Properties:
     #       RestApiId: !Ref ApiGateway
     #       Path: '/'
     #       Method: get
        AuthSignIn:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: '/auth/sign-in'
            Method: post
        AuthSignOut:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: '/auth/sign-out'
            Method: post
    Metadata:
      BuildMethod: makefile
Outputs:
  Endpoint:
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
